// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"SunnyContest/internal/controller"
	"SunnyContest/internal/services"
)

// Injectors from user.wire.go:

func InitUserRouterHandler() (*controller.UserController, error) {
	iUserService := services.NewUserService()
	userController := controller.NewUserController(iUserService)
	return userController, nil
}
