// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type SfUser struct {
	ID           int64     `json:"id"`
	Username     string    `json:"username"`
	Password     string    `json:"password"`
	Role         int32     `json:"role"`
	Status       int32     `json:"status"`
	Token        string    `json:"token"`
	TokenExpried int64     `json:"token_expried"`
	CreatedTime  time.Time `json:"created_time"`
	UpdatedTime  time.Time `json:"updated_time"`
}
