// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	ChangePassword(ctx context.Context, arg ChangePasswordParams) (SfUser, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (SfUser, error)
	DeleteUser(ctx context.Context, id int64) error
	GetUserByEmail(ctx context.Context, username string) (SfUser, error)
	GetUserByID(ctx context.Context, id int64) (SfUser, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (SfUser, error)
}

var _ Querier = (*Queries)(nil)
