server:
    port: 8080
    mode: "dev"
postgresql:
    dbDriver: postgres
    dbSource: "postgresql://root:secret@localhost:5432/SunnyContest?sslmode=disable"
logger:
    log_level: debug
    file_log_name: "./storages/logs/dev.001.log"
    max_size: 500
    max_backups: 3
    max_age: 28
    compress: true
